### ISSUE TITLE
Allow people to add a 2nd card on the kiosk with there 1st card.

### ISSUE THREAD

**Issue by JasperWallace** [londonhackspace/hackspace-foundation-sites#111]
Not sure how easy this will be cos of the way the card reader works?

**Comment by marksteward** [comment]
Do we let people log in with their card already? A "card A, card B, card A" flow might work.

**Comment by JasperWallace** [comment]
I'm leaning towards not doing this, would be too easy for people to just add someone else's card.

**Comment by cepmenderer** [comment]
Card A, "add card", <password>, Card B, Card A.

Would ensure that no-one could take advantage of an accidental failure to log out.

**Comment by zymurgic** [comment]
I agree with Jasper. If a card is left lying around, it makes it too easy to inherit all their tool permissions, and then return card to original owner. Needs more secure authentication, and nowadays we have the QR code link to login, so logging is isn't a problem, even for those people with complicated passwords.
