### ISSUE TITLE
Configure the firewall and DNS so that Turing has access to acserver for tools status update

### ISSUE THREAD

**Issue by mentarus** [londonhackspace/hackspace-foundation-sites#114]
Currently relying on an SSH tunnel which is bad. So all we'd need is a firewall rule that allows turing to access acserver:1234 through the firewall

**Comment by JasperWallace** [comment]
DNS and ipv6 access already work, I've changed ACSERVER_ADDRESS to "http://acserver.london.hackspace.org.uk:1234" in config.php.
