### ISSUE TITLE
Create python skeleton app

### ISSUE THREAD

**Issue by russss** [londonhackspace/hackspace-foundation-sites#115]
In order to let us write new code in Python rather than PHP. This involves doing some session shenanigans to look up PHP session cookies.

Depends on #85 or I fear we're going to start seeing sqlite locking issues.

**Comment by marksteward** [comment]
Flask or Django? Jasper's redone acserver in Django, and it would give us DB migrations for free. On the other hand, Flask is still much lower complexity out of the box.

**Comment by JasperWallace** [comment]
I'm obviously happier with Django. The only issue is that If we're going to use the Django ORM it would probably be better to let the ORM define tables itself - which might end up different from russ's ones :cry:

**Comment by russss** [comment]
It's easy to do that with `manage.py inspectdb` so it's not a huge issue. I'm happy to have django manage the DB once it's working.

I think perhaps django is the right way forward in this case. I can have a go at creating a skeleton app tomorrow and see if there are any issues.

**Comment by marksteward** [comment]
I've looked at the session information and it seems there's nothing security-sensitive that we'd need to start migrating pages over. acf2416 adds a page that returns something like this for a logged-in user:

```
{"user_id":48,"type":"persistent","expires":1477435339,"suppress_profile_notification":null}
```

We now need to write a user loader that fetches this page with the user's cookie and looks up the user in the existing DB.

**Comment by marksteward** [comment]
Done with 5e17aaa and bf004b8
