### ISSUE TITLE
Add a name badge sticker

### ISSUE THREAD

**Issue by JasperWallace** [londonhackspace/hackspace-foundation-sites#133]
See what the dimensions of those plastic pouches are so people can re-use the name badges, get a few hundred pouches and some lanyards.

Also "Guest of ..." stickers as well, and maybe "Visitor" too?

**Comment by JasperWallace** [comment]
Also Trustees get a special badge

**Comment by SciStarborne** [comment]
If we're going with lanyards, a large proportion of people will likely start using them with the ID card holders for their RFID cards. So assume credit-card sized.

**Comment by pinski1** [comment]
See here for the Cambridge Makespace solution: https://github.com/Makespace/Badger

**Comment by JasperWallace** [comment]
Working now, (tho no special trustee badge), we might want an option to reduce the amount of data on it (I guess people cal always use a pen). I'll leave this open for a bit if anyone has anything to add.

**Comment by JasperWallace** [comment]
Stefan would like the option to limit the info on the badge.

**Comment by JasperWallace** [comment]
fixed with cf164cb235da0ec1eeb2a41cdf2f7e3fa4f9b51d and a30109038a4e9d5fa8efd20e6b62b9ca443a24a4
