### ISSUE TITLE
Initial django app in parallel with PHP

### ISSUE THREAD

**Issue by russss** [londonhackspace/hackspace-foundation-sites#142]
We'd like to start the python migration by having a django app running, in parallel with the PHP app. I've made a start on this in the `python` branch. Let's just get the minimum possible working first and running on live, authentication is in #143.

**Comment by russss** [comment]
If I remember correctly, the sticking point I hit with this is that the Flourish framework errors out if there are tables in the database it doesn't know about. This isn't great so we need a way of working around this.

(As a nasty hack, could we have the django tables in a different postgres schema to the flourish ones?)

**Comment by marksteward** [comment]
Separate schema sounds good to me.

**Comment by marksteward** [comment]
I've given up on the separate schema plan as neither Flask nor Django copes well with schemas. Instead, I've patched Flask to only look at a chosen subset of tables with c6a01ab

**Comment by marksteward** [comment]
I think this is complete. The first thing I'm going to migrate is storage-requests-cron.php from #147.
