### ISSUE TITLE
Share authentication info between PHP and Django

### ISSUE THREAD

**Issue by russss** [londonhackspace/hackspace-foundation-sites#143]

**Comment by russss** [comment]
This may be a bit complex. Perhaps the best way to go initially is to keep PHP as the source of truth for authentication, and have Django make an API call to the PHP app to validate the session cookie (and perhaps then issue a Django session). This may need some custom Django authentication logic.

Logout might require PHP to make an API call to the django app to invalidate the session.

**Comment by marksteward** [comment]
https://london.hackspace.org.uk/session.php returns the current user_id and expiry time

**Comment by marksteward** [comment]
We have the following scenarios to consider:

- log in from PHP
- log out from PHP
- log in from Django
- log out from Django
- disabling an account
- session invalidation on password change
- privilege granting (e.g. admin access)
- privilege revocation

I suggest we redirect all Django requests to PHP to make things easier.

When logging in, we set the user session details in their cookie, and then check that in Python with a loopback request to PHP. This could probably be done on every request without a noticeable delay.

Django typically tracks a session_auth_hash which is validated against the user's password hash on each request, implying a DB call anyway. We could tie this session_auth_hash to the PHP session.

**Comment by marksteward** [comment]
Permission changes work fine in the admin pages, and while disabling an account doesn't log them out, that's because the PHP code doesn't check it.
