### ISSUE TITLE
Decide on a User model for Django

### ISSUE THREAD

**Issue by marksteward** [londonhackspace/hackspace-foundation-sites#146]
There are are two models to consider: the Django built-in one (`last_login`, `first_name`, `last_name`, `is_staff`, `is_active`, `date_joined`, `username`, and permissions delegated by groups) and the LHS one (`full_name`, `subscribed`, `terminated`, `admin`, `nickname`, and a separate profile).

We can tie these two models together in a one-to-one relationship, which would potentially make it easier to keep the LHS junk separate and safe to change, and gives us permissions and groups for free. This is called the profile model, which may be confusing as we already have optional profiles in the `users_profiles` table. Additionally, `first_name` and `last_name` are `NOT NULL`, but we can work around that. We'd need to create rows in the Django table on logon if they don't already exist.

Or we can simply use the LHS one as a custom user model, and add any permissions system later. It's claimed in the documentation to be hard to switch back from this to the built-in Django one, because the `user_id` column is referenced in apps like Django admin, so we probably only want to do this if we're sure we won't ever want Django's model.

**Comment by marksteward** [comment]
Fwiw, I'm strongly leaning towards the latter, but would like to hear if anyone else has thoughts.

**Comment by russss** [comment]
Yeah it's highly recommended to start with a custom user model anyway (or at least a subclass of the default), otherwise it's harder to make changes later. I think a custom user model is the way to go.

**Comment by russss** [comment]
In fact, can we back Django's user model onto the same table as we use with PHP? Might make things simpler but I suspect it may also generate issues.

**Comment by marksteward** [comment]
Yeah we'd subclass AbstractBaseUser regardless. We can use the same table as PHP, mapping what we can and raising NotImplemented for attempts to add permissions - that's the second option.
