### ISSUE TITLE
Storage System not marking as passed deadline

### ISSUE THREAD

**Issue by padski** [londonhackspace/hackspace-foundation-sites#147]
IE a bit properly fucked

**Comment by marksteward** [comment]
Got an example?

**Comment by padski** [comment]
653

827

761

810

And most of the rest

**Comment by marksteward** [comment]
Yeah, see what you mean - I was looking at the wrong thing.

**Comment by marksteward** [comment]
storage-requests-cron.php, which sends emails but also updates the DB, hasn't been migrated to Postgres

**Comment by marksteward** [comment]
Fixed by 42d5052
