### ISSUE TITLE
Fix ACNode Tools information to not include Doorbot code

### ISSUE THREAD

**Issue by kraptv** [londonhackspace/hackspace-foundation-sites#165]
https://london.hackspace.org.uk/members/tools.php is now showing Doorbot ACNodes as tools which is not really appropriate for their use.

Please remove or ignore any ACNode line that has a 'doorbot' or 'Doorbot' in the name that is used for general hacking.

Special-skills doorbots such as electronics lab, biohacking laboratory, amateur radio room, or possibly others probably SHOULD be listed to show member training entitlements.

**Comment by mich181189** [comment]
I think rather than using string bashing to deermine it's a doorbot, we should add a type field to the tool record on acserver then either only return non-door records in the json the website consumes (which would make this an acserver task) or the website filters out by type

**Comment by JasperWallace** [comment]
+1 for a tool type field.

**Comment by JasperWallace** [comment]
These:

* https://github.com/londonhackspace/acserver-django/commit/128066b9dd2e39f331289d42058f72578836b83c
* https://github.com/londonhackspace/acserver-django/commit/a9bd3b321f685fc7c6882f7c7fa06428757b994e

commits enable changing the website.
