### ISSUE TITLE
Update LDAP info to have better wifi links - maybe explain differently why an LDAP account.

### ISSUE THREAD

**Issue by kraptv** [londonhackspace/hackspace-foundation-sites#166]
There should be some incentive for people to use logins for wifi and other hackspace integration. 

We will start to use LDAP for workstations around as well - Tesla will likely have LDAP login and the temporary guest logins as well, for example. 

* Consider changing this nomenclature of "log into our various servers" to be more than just servers (computer workstations, servers, and related resources)

* Federated wifi link to https://spacefed.net/wiki/index.php/SpaceFED is a 404. Please fix/update.

**Comment by JasperWallace** [comment]
fixed with a5c8fc140ae3ffc57502d08663a1308cccf05382
