### ISSUE TITLE
When migrating from bank transfer payments to GoCardless, remind users to cancel standing order

### ISSUE THREAD

**Issue by zymurgic** [londonhackspace/hackspace-foundation-sites#193]
When migrating a member payments to GoCardless having previously paying by bank transfer, remind the member, either by email or on-screen, to cancel their standing order if they don't want to pay twice.

**Comment by zymurgic** [comment]
(only need to mention this if there had been previous transactions in the past 30 days via bank transfer), for new members, it should not be mentioned.

**Comment by mich181189** [comment]
@zymurgic how's this look?
![lhs-site-please-cancel-your-so](https://user-images.githubusercontent.com/174898/76048902-e5c96600-5f5d-11ea-92bb-12bd93f54088.png)
