### ISSUE TITLE
Prevent blank doorbot nicknames

### ISSUE THREAD

**Issue by padski** [londonhackspace/hackspace-foundation-sites#201]
This makes it extremely hard to identify occupants, even for Trustees

**Comment by zymurgic** [comment]
Looking at the database, I don't think anyone has actually done that. What's happening seems to be that the mqtt listeners, when they try to look up the users name / nickname on acserver, that's failing for some reason, and it blindly goes ahead and announces a null name on irc (and other outputs)

**Comment by padski** [comment]
Yeah just clicked........

**Comment by padski** [comment]
Lol

**Comment by zymurgic** [comment]
Just for completeness, I've changed the cards.php script to prevent users from pretending to be others by putting whitespace after the nick. It now trims leading and trailing whitespace before committing to the database.
