### ISSUE TITLE
[BUG] Storage requests page not loading

### ISSUE THREAD

**Issue by darigovresearch** [londonhackspace/hackspace-foundation-sites#224]
May be good to replace this with a placeholder page saying "Coming soon" while we set a system up at the interim space

**Comment by tolland** [comment]
This seems to be a consequence of requests to other pages in the site hanging the storage request page. Once they are excluded this page works fine.
![image](https://github.com/londonhackspace/hackspace-foundation-sites/assets/91288/fae86fec-4df9-48ae-830f-dc9fdc48005e)

Closing in respect of the other problem
