### ISSUE TITLE
Storage system marks as Deadline Passed at original date when extended. 

### ISSUE THREAD

**Issue by padski** [londonhackspace/hackspace-foundation-sites#94]
Storage system marks as Deadline Passed at original date when extended. 
Also does not notify of extension.

**Comment by marksteward** [comment]
Reported by Julia for https://london.hackspace.org.uk/storage/212:

```
2:12pm 15th Sep | Status changed to Extended by Juliet Green
5:00am 18th Sep | Day after removal, reminder email sent to owner
5:00am 18th Sep | Status automatically changed to Passed Deadline
```

**Comment by marksteward** [comment]
Possibly caused by https://github.com/londonhackspace/hackspace-foundation-sites/blob/master/bin/storage-requests-cron.php#L68-L70 ?
